export const data = [
  {
    title: "Agency website",
    cover: "/images/mockups/main-mk-agency-website.png",
    desc: "Landing page de un sitio web de la agencia AV0CAD0, uso de NextJS, React Router & CSS.",
    site: "https://agency-website-sandy.vercel.app",
    category: "react",
    repository: "https://github.com/Artwot/agency-website",
  },
  {
    title: "Bienes Raíces",
    cover: "/images/mockups/main-mk-real-estate.png",
    desc: "Página que permite buscar casas, villas y departamentos, obteniendo los datos de la API de Bayut.",
    site: "https://real-estate-app-lovat.vercel.app/",
    category: "react",
    repository: "https://github.com/Artwot/real-state-app",
  },
  {
    title: "Super Mario World Clone",
    cover: "/images/mockups/main-mk-super-mario.png",
    desc: "Clon del sitio web del videojuego de Super Mario, con la finalidad de practicar tailwindcss.",
    site: "https://supermario-3d-world.netlify.app",
    category: "html",
    repository: "https://github.com/Artwot/super-mario-tailwind-css",
  },
  {
    title: "Sunnyside agency",
    cover: "/images/mockups/main-mk-sunnyside.png",
    desc: "Landing Page de la agencia de Sunnyside, construido para Frontend Mentor Challenge.",
    site: "https://sunnyside-agency-lp.netlify.app/",
    category: "html",
    repository: "https://github.com/Artwot/sunny-agency-landing-page",
  },
  {
    title: "Starbucks landing page",
    cover: "/images/mockups/main-mk-starbucks.png",
    desc: "Clon de la página principal de Starbucks, para practicar maquetación.",
    site: "https://starbucks-landing-page-clone.netlify.app/",
    category: "html",
    repository: "https://github.com/Artwot/starbucks-clone",
  },
  {
    title: "Order Summary",
    cover: "/images/mockups/main-mk-order.png",
    desc: "Maquetación de un componente para aceptar un pago. Reto de la página Frontend Mentor",
    site: "https://order-summary-challenge-artwot.netlify.app/",
    category: "html",
    repository: "https://github.com/Artwot/Order-summary-component",
  },
];
