import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Topbar from "../components/Topbar";
import Intro from "../components/Intro";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import { useState } from "react";

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <div className="">
      <Head>
        <title>Jorge Sarabia - Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/jorge.png" />
      </Head>
      {/* Topbar */}
      <Topbar menuOpen={menuOpen} setMenuOpen={setMenuOpen} />
      <div className="w-full h-[calc(100vh-5rem)] top-20 relative">
        <Intro />
        <About />
        <Projects />
        <Contact />
      </div>
    </div>
  );
}
