import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Topbar from "../components/Topbar";
import Intro from "../components/Intro";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import { useState } from "react";
import Menu from "../components/Menu";
import { data } from "../pages/api/data";

export default function Home({ projects }) {
  return (
    <div className="">
      <Head>
        <title>Jorge Sarabia - Frontend Developer</title>
        {/* Iconos Font Awesome */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
          crossOrigin="anonymous"
          referrerpolicy="no-referrer"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/jorge.svg" />
      </Head>
      <Intro />
      <Skills />
      <Projects projects={projects} />
      <About />
      <Contact />
      <br />
      <div className="flex justify-center items-center py-10">
        <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">
          <i className="far fa-smile text-slate-900 text-xl"></i>
        </a>
      </div>
      <hr className="w-[90%] mx-auto border border-solid " />
    </div>
  );
}

// Fetch the data
export const getStaticProps = async () => {
  const projects = data;
  return {
    props: { projects },
  };
};
