import Head from "next/head";
import Intro from "./Intro";
import About from "./About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import { data } from "./api/data";

export default function Home({ projects }) {
  return (
    <div className="">
      <Head>
        <title>Jorge Sarabia - Software Engineer</title>
        {/* Iconos Font Awesome */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/jorge.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      </Head>
      <main className="">
        <Intro />
        <About />
      </main>
    </div>
  );
}
